name: taski
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  shimmer: ^3.0.0
  bloc_test: ^10.0.0
  flutter_svg: ^2.0.17
  sqflite: ^2.4.1
  path: ^1.9.0

dev_dependencies:
  my_custom_lints:
    git:
      url: https://github.com/WemersonDamasceno/my_custom_lints.git
      ref: main
  flutter_test:
    sdk: flutter 
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4  
  flutter_launcher_icons: ^0.13.1
  sqflite_common_ffi: ^2.3.2





flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/task_icon.png"


flutter:
  uses-material-design: true
  assets:
    - test/integration_test/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
    
      
